### ISSUE TITLE
NPC Skins doesn't update

### ISSUE THREAD

**Issue by Fargus-Van-Crystal-de-Mindark** [AlonsoAliaga/AlonsoLeaderboards#2]
Hello, it is not normal that the skins doesn't update when the sign do it

![image](https://user-images.githubusercontent.com/20026629/101995763-dd604180-3ccc-11eb-8d0b-95a49b6570ce.png)

Do you know what is the problem?

I'm on Paper 1.16.3, using your latest version of leaderboards

**Comment by AlonsoAliaga** [comment]
Hello, skin should update normally. Right click the entity, it opens inventory leaderboard? If so, select the npc, run /npc remove
and add it again, check if it updates again, if not, do the same, that means entity wasn't linked to leaderboard susccessfully for some reason

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
Thanks for your prompt reply.
I already did what you said and anything has changed. The skin doesn't change.

I give you a fawe debugpaste to let you verify yourself plugins and logs in the server.

https://athion.net/ISPaster/paste/view/cdd2e20beae6437f9c0283e146f104ff

**Comment by AlonsoAliaga** [comment]
Latest version is 1.3-BETA, you are using 1.2-BETA try updating to latest version.
If issue persists after restart, join my discord server (https://alonsoaliaga.com/discord) to be able to reply faster

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
Problem has been fixed with patch 1.3
thank you
