### ISSUE TITLE
Task #92 for AlonsoLeaderboards v1.4-BETA generated an exception java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Bossslime** [AlonsoAliaga/AlonsoLeaderboards#6]
I've been getting this error in console: https://pastebin.com/kSR5cakF

I know the placeholders that I have been using are valid and do return numbers as I use them in other places on my server. This error normally occurs when a player joins the server or every 5 or so minutes

**Comment by AlonsoAliaga** [comment]
Hello, share what is above that error (if possible, since start up until the first error)

**Comment by Bossslime** [comment]
Can I dm it to you on discord by chance?
if so what is your discord

**Comment by AlonsoAliaga** [comment]
No problem, discord is in all my plugin's posts: https://alonsoaliaga.com/discord

**Comment by Bossslime** [comment]
I created a ticket!
