### ISSUE TITLE
Error updating global leaderboard: Communications link failure

### ISSUE THREAD

**Issue by 9i7zy** [AlonsoAliaga/AlonsoLeaderboards#8]
[02:02:22 INFO]: [AlonsoLeaderboards] Loading placed leaderboards..
[02:02:22 INFO]: [AlonsoLeaderboards] Armor stand is not available anymore for leaderboard 'alevels-level'. Skipping..
[02:03:37 INFO]: [AlonsoLevels] Error updating global leaderboard: Communications link failure

The last packet successfully received from the server was 600,157 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago.

**Comment by 9i7zy** [comment]
The leaderboards I have set will often fail for no reason. Such a prompt will be displayed in the background

**Comment by AlonsoAliaga** [comment]
`[02:02:22 INFO]: [AlonsoLeaderboards] Loading placed leaderboards..
[02:02:22 INFO]: [AlonsoLeaderboards] Armor stand is not available anymore for leaderboard 'alevels-level'. Skipping..`
Sorry but this issue cannot be fixed for now.
Problem:
- Your server loads the plugin before the world is loaded so no entities are available at the moment armorstands are checked.
Temporary soluction (at least)
- Use NPCs from Citizens (might work without issues)
Reason that it cannot be fixed now:
- Plugin is not available in the source code form for now

`[02:03:37 INFO]: [AlonsoLevels] Error updating global leaderboard: Communications link failure
The last packet successfully received from the server was 600,157 milliseconds ago. The last packet sent successfully to the server was 1 milliseconds ago.`
Join our discord server and share full console log in a bin like pastebin

**Comment by 9i7zy** [comment]
Can you tell me what is the variable of alevels-level ranking? The default configuration file can modify it too little, even if I manually enter it, it still cannot be displayed normally

**Comment by AlonsoAliaga** [comment]
I don't understand what you mean, all configurations are in AlonsoLevels/config.yml, if something is not there you can't modify it.
I simply can't make everything customizable. It's simply not possible

**Comment by 9i7zy** [comment]
Has been solved, thank you, your plug-in is great
